### PR TITLE
Fix travis-ci and appveyor.

### PR DESCRIPTION
**Pull request by sighingnow**

### CODE REVIEW

**Comment by winterland1989** [comment]
Nice. Can you run the benchmarks in `bench/libuv` now? let's check how libuv perform on windows :smile:

**Comment by sighingnow** [comment]
OK.

**Comment by sighingnow** [comment]
Besides, I have a question about how does our `ci/circleci` work? I didn't find the configuration file in our repo.

**Comment by winterland1989** [comment]
I haven't used that yet, i din't use circle ci yet, did i?

**Comment by sighingnow** [comment]
CI failed due compile errors in current code....

**Comment by sighingnow** [comment]
Maybe the circleci was enabled by accident ?

ci

**Comment by sighingnow** [comment]
Currently the changeset in #5 is not included in libuv branch, then I can't build the benchmark executable on windows. Shall I merge master to libuv branch ?

**Comment by winterland1989** [comment]
Ah, yes. BTW, i have to check where to disable circle CI...

**Comment by sighingnow** [comment]
`System.Posix.Signals` from the `unix` package is used in `UVManager`.

**Comment by winterland1989** [comment]
Ah, my bad, that's because i'm trying to disable `SIGVTALRM`, but that's not necessary, so please remove it.

**Comment by sighingnow** [comment]
OK. I just found that the imported `sigVTALRM` was not used in code.

**Comment by winterland1989** [comment]
The relevant  issue is here: https://github.com/libuv/help/issues/20

**Comment by sighingnow** [comment]
Unfortunately when execute libuv, I got

~~~
libuv.EXE: thread blocked indefinitely in an MVar operation
~~~

I'm trying to find out why.

**Comment by winterland1989** [comment]
> libuv.EXE: thread blocked indefinitely in an MVar operation

I haven't come across this exception on linux yet, but take a look at `uvmFreeSlotList` field, i use it as the main lock.

BTW: I have removed circle CI from this project, thanks for point it out.

**Comment by sighingnow** [comment]
OK. I'll do further investigation tomorrow.

**Comment by sighingnow** [comment]
All threads blocked on `takeMVar (indexArr btable slot)` in the `readInput` method of `instance Input TCP`.

Update:

I also notice that the value of `c` in Line 166 (peekEventQueue) of `UVManager.hs` is `0`.

**Comment by winterland1989** [comment]
That means libuv didn't get any event during `uv_run` , which is possible, and in that case we don't unblock those `MVar` s . But how is that be reported by RTS? We are looping `uv_run` after all.

**Pull request merged**
